### ISSUE TITLE
Investigate auth service providers

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/drawbridge#173]
Instead of implementing our own custom auth support, we should look into different options on the market already to get us faster to MVP. Some options:
- https://auth0.com/
- https://workos.com/
- https://www.keycloak.org/
- https://goauthentik.io/
- https://ory.sh/
- https://www.cloud-iam.com/

Things to take into consideration:
- Possibility to use our own branding
- Clear and simple migration path
- Standard compliance (related to point above). Ideally, we want to use something that uses a well-defined standard protocol.
- Available tooling for integration
- Ability and ease of self-hosting the service or spinning up a custom instance

This may affect #7

**Comment by rjzak** [comment]
Adding https://www.cloud-iam.com/ (hosted Keycloak)

**Comment by rvolosatovs** [comment]
So it seems that we want something that supports OIDC and propbably is on this list https://openid.net/developers/certified/

**Comment by rvolosatovs** [comment]
We went with auth0, which is by far the simplest and quickest to start with, feature-complete, and it also ticks all the boxes, since we can retrieve data about all our users, including provider-specific tokens via their API. There's functionality to trivially create a new tenant, we can customize a lot (but not everything).

Eventually we want to switch to https://www.ory.sh/, which we should be able to host ourselves completely and with some luck, run it in a keep one day. At the time of writing, their cloud offering is missing OIDC (Ory Hydra) functionality and we do not have the resources available to host it ourselves. The functionality should be available by Q4 this year, maybe earlier https://github.com/ory/cloud/discussions/50#discussioncomment-2848518. Let's revisit this then.
