### ISSUE TITLE
Reenable `app` crate test

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/drawbridge#186]
Unfortunately, `reqwest` does not support `async-std` and `futures`.
Experimentation with tokio compatibility layers to work around these issues did not succeed, so I disabled the test in `app` crate in https://github.com/profianinc/drawbridge/commit/e84c7efcdafd97361b1fc0fc8acb26fa941733b8.
The tests should be reworked with a different HTTP(s) client (probably `ureq`, which we already use in the `client` crate) and the commit should be reverted.

As part of this effort it *may* be worthwhile refactoring the test to make it smaller (and therefore easier to migrate) by adopting the `Entity` pattern we now use in [`client` crate](https://github.com/profianinc/drawbridge/blob/e84c7efcdafd97361b1fc0fc8acb26fa941733b8/crates/client/src/entity.rs) and [`app` crate](https://github.com/profianinc/drawbridge/blob/e84c7efcdafd97361b1fc0fc8acb26fa941733b8/crates/app/src/store/entity.rs)

**Comment by rjzak** [comment]
The title says to "Reenable app crate tests" but the description says "...so disable the test in app crate...". Simply reverting the last commit isn't enough, as it generates Tokio errors `thread 'app' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'`.

**Comment by rvolosatovs** [comment]
Sorry, copy-pasted from commit description, should have reworded to better convey the purpose. Just fixed the description, please let me know if it is better worded now!
