### ISSUE TITLE
Bump max upload size to drawbridge.

### ISSUE THREAD

**Issue by platten** [profianinc/drawbridge#243]
The Greenhouse monitor WASM demo is 40 MB, and I am getting a "413 Request Entity Too Large" response when uploading it. Might be useful to bump this to 50MB or more to give us some breathing room.

**Comment by rvolosatovs** [comment]
Drawbridge does not limit the size of uploads, this belongs in https://github.com/profianinc/benefice, please move

**Comment by rvolosatovs** [comment]
Not sure if this in an infrastructure issue, or Drawbridge, reopening for now

**Comment by platten** [comment]
![image](https://user-images.githubusercontent.com/773636/180227369-dae04157-d041-47c0-bee2-28631e7a2a53.png)

**Comment by rvolosatovs** [comment]
@platten can you please try with a local Drawbridge?
