### ISSUE TITLE
Allow incomplete Meta

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/drawbridge#55]
Complete `Meta` is required on creation of tags and trees in the latest draft. We want to store `Meta` for all objects we store (tags, trees, repos).
It may greatly simplify the API and improve usability if this requirement would be (partially) dropped.
`PUT` of an object can (optionally compute) and return the complete `Meta` as a response.
`Content-Type` is always required, but `Content-Length` and `Content-Digest` can be computed after the body is received.

We could compute all digests and count the length (if those are not specified) and return that as a response. Client can then verify the digest and length to ensure correctness.

For tag service, for example, it means that users can create tag trivially even from command line via e.g. `curl`

@npmccallum what do you think?

**Comment by npmccallum** [comment]
If you can make it work, sure!
